language: go

addons:
  apt:
    sources:
      - sourceline: 'ppa:git-core/ppa'
    packages:
      - git
      - upx-ucl

go:
  - "1.10"

script:  make
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - smarti_osx
    - smarti
    - smarti.exe
  skip_cleanup: true
  on:
    tags: true